#!/usr/bin/env bash
# This script uses switch and case

count=1

while [ $count -le 20 ]
do
	case $count in
		4)
			echo $count
			echo "bad lack from China"
			;;
		9)
			echo $count
			echo "bad lack from Japan"
			;;
		17)
			echo $count
			echo "bad lack from Italy"
			;;
		*)
			echo $count
			;;
	esac
	((count++))
done
