#!/usr/bin/env bash
# This script prints for 8 and 4

count=1

while [ $count -le 10 ]
do
	if [ $count -eq 4 ]; then
		echo "bad luck"
	elif [ $count -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((count++))
done
