#!/usr/bin/env bash
# This script displays clock

hours=0
echo "Hour: $hours"
while [ $hours -lt 12 ]
do
	minutes=1
	while [ $minutes -le 59 ]
	do
		echo "$minutes"
		((minutes++))
	done
	((hours++))
	echo "Hour: $hours"
done
