#!/usr/bin/env bash
# This script changes IPs
sudo cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
sed -i '1s/^/8.8.8.8\tfacebook.com\n/' ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
